import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { getPool } from '@nexus/core';

export function registerInsightTools(server: McpServer): void {
  // ── Proactive Insights ──────────────────────────────────
  server.tool(
    'nexus_insights',
    'List recent proactive insights generated by the platform (PIE pipeline)',
    {
      limit: z.number().optional().default(10).describe('Max insights'),
      delivered: z.boolean().optional().describe('Filter by delivery status (omit for all)'),
    },
    async ({ limit, delivered }) => {
      const pool = getPool();
      const conditions = ['1=1'];
      const params: unknown[] = [limit];

      if (delivered !== undefined) {
        conditions.push(delivered ? 'delivered_at IS NOT NULL' : 'delivered_at IS NULL');
      }

      const { rows } = await pool.query(
        `SELECT id, title, body, insight_type, confidence, urgency,
                category, created_at, delivered_at
         FROM proactive_insights
         WHERE ${conditions.join(' AND ')}
         ORDER BY created_at DESC
         LIMIT $1`,
        params,
      );
      return { content: [{ type: 'text' as const, text: JSON.stringify({ count: rows.length, insights: rows }, null, 2) }] };
    },
  );

  // ── LLM Costs ───────────────────────────────────────────
  server.tool(
    'nexus_llm_costs',
    'LLM usage and cost breakdown by agent, model, and time period',
    {
      period: z.enum(['24h', '7d', '30d']).optional().default('7d').describe('Time window'),
    },
    async ({ period }) => {
      const pool = getPool();
      const interval = period === '24h' ? '1 day' : period === '7d' ? '7 days' : '30 days';

      const [byAgent, byModel] = await Promise.all([
        pool.query(
          `SELECT handler as agent, model,
                  COUNT(*)::int as calls,
                  ROUND(AVG(duration_ms))::int as avg_ms,
                  SUM(COALESCE(prompt_tokens,0))::int as total_prompt_tokens,
                  SUM(COALESCE(completion_tokens,0))::int as total_completion_tokens
           FROM agent_llm_log
           WHERE created_at > NOW() - INTERVAL '${interval}'
           GROUP BY handler, model
           ORDER BY calls DESC
           LIMIT 30`,
        ),
        pool.query(
          `SELECT model,
                  COUNT(*)::int as calls,
                  ROUND(AVG(duration_ms))::int as avg_ms,
                  SUM(COALESCE(prompt_tokens,0))::int as prompt_tokens,
                  SUM(COALESCE(completion_tokens,0))::int as completion_tokens
           FROM agent_llm_log
           WHERE created_at > NOW() - INTERVAL '${interval}'
           GROUP BY model
           ORDER BY calls DESC`,
        ),
      ]);

      return {
        content: [{
          type: 'text' as const,
          text: JSON.stringify({
            period,
            by_agent: byAgent.rows,
            by_model: byModel.rows,
          }, null, 2),
        }],
      };
    },
  );
}
